export type Chat = {
  id: string;
  name: string;
  nameEmoji?: string;
  avatar: string; // URL for the image
  lastMessage: string;
  time: string;
  timeColor?: "green" | "default";
  unreadCount?: number;
  unreadType?: "mention" | "normal";
  isTyping?: boolean;
  isDeleted?: boolean;
  isPinned?: boolean;
  hasLocation?: boolean;
  hasLiveActivity?: boolean;
  hasDoubleTick?: boolean;
  hasStoryRing?: boolean;
  hasStatusRing?: boolean;
  isGroup?: boolean;
  isFavourite?: boolean;
};

export const chats: Chat[] = [
  {
    id: "2",
    name: "+234 80 12 34 56 78",
    nameEmoji: "💕",
    avatar: "/profile.jpg",
    lastMessage: "Mom is typing...",
    time: "19:45",
    isTyping: true,
    timeColor: "green",
    unreadCount: 1,
    unreadType: "mention",
    hasStatusRing: true,
  },
  {
    id: "3",
    name: "+229 01 53 44 39 79",
    avatar: "/profile.jpg",
    lastMessage: "I mean he wrecked it! 🤩",
    time: "19:42",
    hasDoubleTick: true,
  },
  {
    id: "4",
    name: "+229 01 83 42 67 30",
    avatar: "/profile.jpg",
    lastMessage: "Say hi to your mom for me.",
    time: "18:23",
  },
  {
    id: "5",
    name: "+229 01 92 06 53 21",
    avatar: "/profile.jpg",
    lastMessage: "Save the clock tower?",
    time: "16:15",
  },
  {
    id: "6",
    name: "+229 01 40 33 61 22",
    avatar: "/stella.webp",
    lastMessage: "You deleted this message.",
    time: "08:57",
    isDeleted: true,
    hasStatusRing: true,
  },
  {
    id: "7",
    name: "+229 01 46 79 72 66",
    avatar: "/profile.jpg",
    lastMessage: "Location",
    time: "",
    hasLocation: true,
    hasLiveActivity: true,
    unreadCount: 1,
  },
  {
    id: "1",
    name: "Jenny",
    nameEmoji: "❤️",
    avatar: "/profile.jpg",
    lastMessage: 'You reacted 🥲 to "That\'s good advice, Marty."',
    time: "16:14",
    isPinned: true,
    hasStoryRing: true,
  },
  {
    id: "8",
    name: "+229 01 34 77 63 54",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "9",
    name: "+229 01 02 29 89 86",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
  },
  {
    id: "10",
    name: "+229 01 17 37 72 49",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "12",
    name: "+229 01 05 77 32 42",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: true,
  },
  {
    id: "13",
    name: "+229 01 47 56 07 45",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "14",
    name: "+229 01 23 83 75 22",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "16",
    name: "+229 01 37 25 96 44",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "17",
    name: "+229 01 37 72 29 37",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "18",
    name: "+229 01 14 18 70 42",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "19",
    name: "+229 01 81 54 70 29",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    unreadCount: 1,
    hasDoubleTick: false,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "20",
    name: "+229 01 13 58 85 97",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
  },
  {
    id: "21",
    name: "+229 01 75 89 28 38",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "22",
    name: "+229 01 16 25 91 99",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "23",
    name: "+229 01 33 12 83 94",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "24",
    name: "+229 01 65 16 88 07",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
  },
  {
    id: "25",
    name: "+229 01 23 85 35 80",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "26",
    name: "+229 01 81 98 51 92",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "27",
    name: "+229 01 52 63 77 14",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "28",
    name: "+229 01 21 27 14 89",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "29",
    name: "+229 01 68 01 01 20",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "30",
    name: "+229 01 44 41 98 02",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "31",
    name: "+229 01 70 62 80 69",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
  },
  {
    id: "32",
    name: "+229 01 53 43 70 62",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    unreadCount: 1,
    hasDoubleTick: false,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "33",
    name: "+229 01 02 30 56 45",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    unreadCount: 2,
    hasDoubleTick: false,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "35",
    name: "+229 01 78 87 73 21",
    avatar: "/profile.jpg",
    lastMessage: "Hey, how are you?",
    time: "",
    unreadCount: 2,
    hasDoubleTick: false,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
  },
];
