export type Chat = {
  id: string;
  name: string;
  nameEmoji?: string;
  avatar: string; // URL for the image
  lastMessage: string;
  time: string;
  timeColor?: "green" | "default";
  unreadCount?: number;
  unreadType?: "mention" | "normal";
  isTyping?: boolean;
  isDeleted?: boolean;
  isPinned?: boolean;
  hasLocation?: boolean;
  hasLiveActivity?: boolean;
  hasDoubleTick?: boolean;
  hasStoryRing?: boolean;
  hasStatusRing?: boolean;
  isGroup?: boolean;
  isFavourite?: boolean;
  /** Si true, affiche le message réel au lieu du skeleton dans la liste */
  showMessage?: boolean;
};

export const chats: Chat[] = [
  {
    id: "37",
    name: "+229 01 62 14 55 83",
    avatar: "/profile.jpg",
    lastMessage: "Je t'ai écrit sur l'autre numéro",
    time: "20:12",
    hasDoubleTick: true,
    unreadCount: 1,
    showMessage: true,
  },
  {
    id: "38",
    name: "+229 01 77 48 29 11",
    avatar: "/profile.jpg",
    lastMessage: "On a conclu 500k non bro ? ayii 😭",
    time: "20:05",
    hasDoubleTick: false,
    unreadCount: 3,
    showMessage: true,
  },
  {
    id: "2",
    name: "+234 80 12 34 56 78",
    nameEmoji: "💕",
    avatar: "/profile.jpg",
    // Message amoureux en anglais pour ce numéro +234
    lastMessage: "I can't stop thinking about you, you make my heart smile every single day 🥰",
    time: "19:45",
    timeColor: "green",
    unreadCount: 1,
    unreadType: "mention",
    hasStatusRing: true,
    showMessage: true,
  },
  {
    id: "36",
    name: "Natacha 🌹🇳🇬",
    avatar: "/profile.jpg",
    lastMessage: "Baby when are you coming back from travel? I miss you so much ❤️",
    time: "19:38",
    hasDoubleTick: false,
    unreadCount: 2,
    hasStoryRing: true,
    showMessage: true,
  },
  {
    id: "3",
    name: "+229 01 53 44 39 79",
    avatar: "/profile.jpg",
    lastMessage: "J'arrive dans 10 minutes, attends-moi !",
    time: "19:42",
    hasDoubleTick: true,
    showMessage: true,
  },
  {
    id: "4",
    name: "+229 01 83 42 67 30",
    avatar: "/profile.jpg",
    lastMessage: "Tu as vu le truc hier soir ? Incroyable",
    time: "18:23",
    hasDoubleTick: true,
    showMessage: true,
  },
  {
    id: "5",
    name: "+229 01 92 06 53 21",
    avatar: "/profile.jpg",
    lastMessage: "Merci pour tout, vraiment. Tu es formidable 😊",
    time: "16:15",
    showMessage: true,
  },
  {
    // Pas de message affiché pour ce numéro → skeleton conservé
    id: "6",
    name: "+229 01 40 33 61 22",
    avatar: "/stella.webp",
    lastMessage: "",
    time: "08:57",
    hasStatusRing: true,
  },
  {
    id: "7",
    name: "+229 01 46 79 72 66",
    avatar: "/profile.jpg",
    lastMessage: "Localisation",
    time: "",
    hasLocation: true,
    hasLiveActivity: true,
    unreadCount: 1,
    showMessage: true,
  },
  {
    id: "1",
    name: "Jenny",
    nameEmoji: "❤️",
    avatar: "/profile.jpg",
    // Message amoureux en français
    lastMessage: "Tu me manques tellement mon amour, j'ai hâte de te revoir ❤️",
    time: "16:14",
    isPinned: true,
    hasStoryRing: true,
    showMessage: true,
  },
  {
    id: "50",
    name: "+229 01 83 16 54 27",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "16:10",
    hasDoubleTick: true,
    hasStoryRing: false,
  },
  {
    id: "8",
    name: "+229 01 34 77 63 54",
    avatar: "/profile.jpg",
    lastMessage: "On se retrouve à quelle heure ce soir ?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "9",
    name: "+229 01 02 29 89 86",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    // Message amoureux
    lastMessage: "Je pense à toi tout le temps, tu es mon bonheur 💫",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
    showMessage: true,
  },
  {
    id: "51",
    name: "+229 01 34 92 07 61",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "",
    hasStoryRing: true,
    unreadCount: 2,
  },
  {
    id: "10",
    name: "+229 01 17 37 72 49",
    avatar: "/profile.jpg",
    lastMessage: "C'est bon pour demain, confirme-moi s'il te plaît",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "12",
    name: "+229 01 05 77 32 42",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Rappelle-moi quand tu peux, c'est urgent 📞",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: true,
    showMessage: true,
  },
  {
    id: "13",
    name: "+229 01 47 56 07 45",
    avatar: "/profile.jpg",
    lastMessage: "Super nouvelle ! On fête ça ensemble 🎉",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "52",
    name: "+229 01 09 73 28 55",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "",
    hasDoubleTick: false,
    hasStoryRing: false,
    unreadCount: 1,
  },
  {
    id: "14",
    name: "+229 01 23 83 75 22",
    avatar: "/profile.jpg",
    // Message amoureux
    lastMessage: "Mon cœur bat uniquement pour toi, ne l'oublie jamais 💖",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "16",
    name: "+229 01 37 25 96 44",
    avatar: "/profile.jpg",
    lastMessage: "Ça va de ton côté ? Donne-moi des nouvelles 🙏",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "53",
    name: "+229 01 61 83 42 09",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
  },
  {
    id: "17",
    name: "+229 01 37 72 29 37",
    avatar: "/profile.jpg",
    lastMessage: "Ok reçu, je m'en occupe tout de suite",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "18",
    name: "+229 01 14 18 70 42",
    avatar: "/profile.jpg",
    lastMessage: "Tu es disponible demain matin ?",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "19",
    name: "+229 01 81 54 70 29",
    avatar: "/profile.jpg",
    // Message amoureux
    lastMessage: "Chaque jour à tes côtés est le plus beau jour de ma vie 🌹",
    time: "",
    unreadCount: 1,
    hasDoubleTick: false,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "20",
    name: "+229 01 13 58 85 97",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "On mange ensemble ce midi ? Je connais un super endroit",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
    showMessage: true,
  },
  {
    id: "21",
    name: "+229 01 75 89 28 38",
    avatar: "/profile.jpg",
    lastMessage: "Le colis est arrivé, merci beaucoup 📦",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "54",
    name: "+229 01 27 59 38 14",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "",
    hasDoubleTick: false,
    hasStoryRing: false,
    unreadCount: 3,
  },
  {
    id: "22",
    name: "+229 01 16 25 91 99",
    avatar: "/profile.jpg",
    lastMessage: "Je t'aime plus que les mots ne peuvent le dire 😍",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "23",
    name: "+229 01 33 12 83 94",
    avatar: "/profile.jpg",
    lastMessage: "Envoie-moi le document dès que possible",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "24",
    name: "+229 01 65 16 88 07",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "C'était une très bonne réunion aujourd'hui 👍",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
    showMessage: true,
  },
  {
    id: "55",
    name: "+229 01 48 16 73 92",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "",
    hasStoryRing: false,
    hasDoubleTick: true,
  },
  {
    id: "25",
    name: "+229 01 23 85 35 80",
    avatar: "/profile.jpg",
    lastMessage: "Tes yeux sont ma lumière dans l'obscurité ✨",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "26",
    name: "+229 01 81 98 51 92",
    avatar: "/profile.jpg",
    lastMessage: "J'ai transmis le message, pas de souci",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "27",
    name: "+229 01 52 63 77 14",
    avatar: "/profile.jpg",
    lastMessage: "Préviens-moi quand tu es rentré sain et sauf 🙏",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "28",
    name: "+229 01 21 27 14 89",
    avatar: "/profile.jpg",
    lastMessage: "On se voit ce week-end ? J'ai une surprise pour toi 🎁",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "29",
    name: "+229 01 68 01 01 20",
    avatar: "/profile.jpg",
    lastMessage: "Tu es la plus belle chose qui me soit arrivée 💝",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "30",
    name: "+229 01 44 41 98 02",
    avatar: "/profile.jpg",
    lastMessage: "La réponse est non, désolé pour le dérangement",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
  },
  {
    id: "31",
    name: "+229 01 70 62 80 69",
    nameEmoji: "⭐",
    avatar: "/profile.jpg",
    lastMessage: "Bonne nuit mon amour, fais de beaux rêves 🌙",
    time: "",
    hasDoubleTick: true,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: true,
    showMessage: true,
  },
  {
    id: "32",
    name: "+229 01 53 43 70 62",
    avatar: "/profile.jpg",
    lastMessage: "Est-ce que tu as reçu mon virement ?",
    time: "",
    unreadCount: 1,
    hasDoubleTick: false,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "33",
    name: "+229 01 02 30 56 45",
    avatar: "/profile.jpg",
    lastMessage: "Je suis bloqué dans les embouteillages, j'arrive",
    time: "",
    unreadCount: 2,
    hasDoubleTick: false,
    hasStoryRing: false,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  {
    id: "35",
    name: "+229 01 78 87 73 21",
    avatar: "/profile.jpg",
    lastMessage: "Sans toi ma vie n'aurait aucun sens 💞",
    time: "",
    unreadCount: 2,
    hasDoubleTick: false,
    hasStoryRing: true,
    isGroup: false,
    isFavourite: false,
    showMessage: true,
  },
  // --- Chats skeleton (pas de message affiché) ---
  {
    id: "40",
    name: "+229 01 39 27 84 16",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "20:01",
    hasDoubleTick: true,
    hasStoryRing: false,
  },
  {
    id: "41",
    name: "+229 01 88 53 12 74",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "19:55",
    hasStoryRing: true,
    unreadCount: 1,
  },
  {
    id: "42",
    name: "+229 01 04 67 93 28",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "19:30",
    hasDoubleTick: true,
    hasStoryRing: false,
  },
  {
    id: "43",
    name: "+229 01 71 25 48 63",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "18:47",
    hasStoryRing: false,
    unreadCount: 4,
  },
  {
    id: "44",
    name: "+229 01 56 38 07 91",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "18:11",
    hasDoubleTick: true,
    hasStoryRing: true,
  },
  {
    id: "45",
    name: "+229 01 93 41 62 05",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "17:58",
    hasDoubleTick: false,
    hasStoryRing: false,
    unreadCount: 2,
  },
  {
    id: "46",
    name: "+229 01 17 84 35 52",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "17:22",
    hasDoubleTick: true,
    hasStoryRing: false,
  },
  {
    id: "47",
    name: "+229 01 62 09 77 43",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "16:49",
    hasStoryRing: true,
    unreadCount: 1,
  },
  {
    id: "48",
    name: "+229 01 28 51 96 70",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "15:33",
    hasDoubleTick: true,
    hasStoryRing: false,
  },
  {
    id: "49",
    name: "+229 01 45 72 18 39",
    avatar: "/profile.jpg",
    lastMessage: "",
    time: "14:06",
    hasDoubleTick: false,
    hasStoryRing: false,
    unreadCount: 6,
  },
];

